services:
  ids:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ids_full_stack
    privileged: true
    restart: unless-stopped

    ports:
      - "8000:8000"
      - "5173:5173"

    volumes:
      - ./backend/storage:/app/backend/storage
      - ./models:/app/models

    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Kolkata
      - CAPTURE_IFACE=eth0
      - TSHARK_BIN=tshark
      - MODEL_DIR=/app/models

    stdin_open: true
    tty: true
